version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:80'
    env_file:
      - .env.compose
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    env_file:
      - .env.compose
