version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:80'
    env_file:
      - .env.compose
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    env_file:
      - .env.compose
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
